// products.js
const PRODUCTS = [
  { id: 1, title: "Playera Pro Fit", price: 299, type: "Ropa", sizes: ["CH","M","G"], colors: ["Negro","Blanco"], 
    desc: "Playera deportiva ligera y de secado rápido. Ideal para entrenamientos intensos y uso diario.", img: "https://picsum.photos/seed/p1/800/600" },
  { id: 2, title: "Tenis Runner X", price: 1599, type: "Calzado", sizes: ["M","G"], colors: ["Azul","Negro"], 
    desc: "Tenis de running con amortiguación avanzada y suela de alta tracción para largas distancias.", img: "https://picsum.photos/seed/p2/800/600" },
  { id: 3, title: "Shorts Speed", price: 249, type: "Ropa", sizes: ["CH","M","G"], colors: ["Rojo","Negro"], 
    desc: "Shorts ultraligeros que permiten máxima movilidad y transpirabilidad.", img: "https://picsum.photos/seed/p3/800/600" },
  { id: 4, title: "Sudadera Sport", price: 799, type: "Ropa", sizes: ["M","G"], colors: ["Gris","Negro"], 
    desc: "Sudadera cómoda y cálida, ideal para calentamiento y uso casual.", img: "https://picsum.photos/seed/p4/800/600" },
  { id: 5, title: "Calcetas Pro", price: 99, type: "Accesorio", sizes: ["CH","M"], colors: ["Blanco","Negro"], 
    desc: "Calcetas deportivas con soporte anatómico y tejido antirozaduras.", img: "https://picsum.photos/seed/p5/800/600" },
  { id: 6, title: "Backpack Team", price: 599, type: "Accesorio", sizes: ["M"], colors: ["Negro","Azul"], 
    desc: "Mochila con compartimentos para calzado y portátil, resistente y ergonómica.", img: "https://picsum.photos/seed/p6/800/600" },
  { id: 7, title: "Gorra Flex", price: 199, type: "Accesorio", sizes: ["G"], colors: ["Azul","Negro"], 
    desc: "Gorra flexible y transpirable, perfecta para entrenamiento al aire libre.", img: "https://picsum.photos/seed/p7/800/600" },
  { id: 8, title: "Botella Hydrate", price: 149, type: "Accesorio", sizes: ["M"], colors: ["Verde","Negro"], 
    desc: "Botella deportiva térmica con cierre hermético y capacidad 1L.", img: "https://picsum.photos/seed/p8/800/600" },
  { id: 9, title: "Leggings Ultra", price: 499, type: "Ropa", sizes: ["CH","M","G"], colors: ["Negro","Gris"], 
    desc: "Leggings compresivos con cintura alta y costuras planas.", img: "https://picsum.photos/seed/p9/800/600" },
  { id: 10, title: "Sudadera Zip Pro", price: 899, type: "Ropa", sizes: ["M","G"], colors: ["Negro","Azul"], 
    desc: "Sudadera con cierre y bolsillos ocultos, perfecta para movilidad.", img: "https://picsum.photos/seed/p10/800/600" },
  { id: 11, title: "Tenis Court Pro", price: 1699, type: "Calzado", sizes: ["M","G"], colors: ["Blanco","Negro"], 
    desc: "Calzado de cancha con soporte lateral y suela duradera.", img: "https://picsum.photos/seed/p11/800/600" },
  { id: 12, title: "Cinturón Fitness", price: 249, type: "Accesorio", sizes: ["M"], colors: ["Negro"], 
    desc: "Cinturón ajustable para entrenamiento de fuerza.", img: "https://picsum.photos/seed/p12/800/600" },
  { id: 13, title: "Malla Compresiva", price: 399, type: "Ropa", sizes: ["CH","M"], colors: ["Azul","Negro"], 
    desc: "Malla para rendimiento con fibras que evaporan el sudor rápido.", img: "https://picsum.photos/seed/p13/800/600" },
  { id: 14, title: "Guantes Pro", price: 219, type: "Accesorio", sizes: ["CH","M","G"], colors: ["Negro","Gris"], 
    desc: "Guantes para gimnasio con refuerzo en palma y agarre antideslizante.", img: "https://picsum.photos/seed/p14/800/600" },
  { id: 15, title: "Shorts Running", price: 279, type: "Ropa", sizes: ["CH","M","G"], colors: ["Negro","Verde"], 
    desc: "Shorts con forro interno y bolsillos para geles o llaves.", img: "https://picsum.photos/seed/p15/800/600" },
  { id: 16, title: "Top Deportivo", price: 319, type: "Ropa", sizes: ["CH","M"], colors: ["Blanco","Negro"], 
    desc: "Top con soporte medio y tejido suave al contacto.", img: "https://picsum.photos/seed/p16/800/600" },
  { id: 17, title: "Zapatillas Cross", price: 1399, type: "Calzado", sizes: ["M","G"], colors: ["Negro","Rojo"], 
    desc: "Zapatillas multiuso para cross training con sujeción reforzada.", img: "https://picsum.photos/seed/p17/800/600" },
  { id: 18, title: "Faja Recovery", price: 349, type: "Accesorio", sizes: ["M","G"], colors: ["Negro"], 
    desc: "Faja de recuperación lumbar con soporte ajustable.", img: "https://picsum.photos/seed/p18/800/600" },
  { id: 19, title: "Calcetas Pro+ (Pack)", price: 179, type: "Accesorio", sizes: ["CH","M"], colors: ["Blanco","Negro"], 
    desc: "Pack de calcetas con refuerzo en talón y puntera.", img: "https://picsum.photos/seed/p19/800/600" },
  { id: 20, title: "Camiseta Técnica", price: 359, type: "Ropa", sizes: ["CH","M","G"], colors: ["Blanco","Azul"], 
    desc: "Camiseta técnica con costuras planas y ajuste anatómico.", img: "https://picsum.photos/seed/p20/800/600" },
  { id: 21, title: "Mochila Light", price: 449, type: "Accesorio", sizes: ["M"], colors: ["Gris","Negro"], 
    desc: "Mochila ultraligera con compartimento para botellas.", img: "https://picsum.photos/seed/p21/800/600" }
];

export default PRODUCTS;
